version: "3.9"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8081:8080
    volumes:
      - ./backend:/var/www/backend
    command: "air -c .air.toml"
