openapi: 3.0.3
info:
  version: 1.0.0
  title: ACE API
  description: >-
    A sample API that uses a sample-site as an example to demonstrate features in
    the OpenAPI 3.0 specification
servers:
  - url: 'http://localhost:82'
paths:
  # admin
  /admin/v1/users/login:
    $ref: "./paths/admin/users.yml"
